name: Storybook
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Add pnpm
        uses: pnpm/action-setup@v2

      - name: Install pnpm
        run: |
          pnpm i

      - name: Install and Build
        run: |
          pnpm run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: storybook-static
          
